apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  datasource:
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: prometheus
    type: prometheus
    url: 'http://prometheus-operated:9090'
  instanceSelector:
    matchLabels:
      app: grafana
  plugins:
    - name: grafana-clock-panel
      version: 1.3.0
  resyncPeriod: 5m
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-strimzi
  labels:
    app: grafana
spec:
  ingress:
    enabled: 'true'
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "root"
      admin_password: "secret"
    auth:
      disable_login_form: 'false'
      disable_signout_menu: 'true'
    auth.basic:
      enabled: 'true'
    auth.anonymous:
      enabled: 'false'
  dashboardLabelSelector:
    - matchExpressions:
        - {key: app, operator: In, values: [grafana]}
