apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: demo
  name: user-demo
  namespace: strimzi-demo
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: greetings
          patternType: literal
        operations:
          - Read
          - Describe
          - Write
          - Create
        host: '*'
      - resource:
          type: group
          name: my-demo-group
          patternType: literal
        operations:
          - Read
        host: '*'