kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  labels:
    strimzi.io/cluster: demo
  name: greetings
  namespace: strimzi-demo
spec:
  partitions: 3
  replicas: 2
  topicName: greetings
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
